version: "2.4"

services:
  oracle-keycloaklab:
    image: ghcr.io/jeoliveira045/oracle-db
    ports:
      - 1521:1521
    volumes:
      - ./src/main/resources/docker.oracle/:/docker-entrypoint-initdb.d/startup

  keycloak-lab:
    image: quay.io/keycloak/keycloak:23.0.5
    ports:
      - 8085:8085
    command: ["start-dev","--http-port","8085"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

