spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: KEYCLOAKLAB
    password: KEYCLOAKLAB
    driver-class-name: oracle.jdbc.driver.OracleDriver # Driver JDBC do Oracle
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8085/realms/springboot-lab
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: springboot-lab
#            authorization-grant-type: authorization_code
#            scope: openid
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8085/realms/springboot-lab
keycloak:
  # configs do realm
  realm: springboot-lab
  auth-server-url: http://localhost:8085/auth
  ssl-required: external
  #configs do client

  resource: springboot-angular-lab-backend
  bearer-only: true
  #configs da secret do realm
  credentials:
    secret: e2a172f5-222b-49b6-bbef-1ef0901143f9
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  security-constraints[0]:
    authRoles[0]: ROLE_ADMIN
  securityCollections[0]:
    patterns: /admin
  security-constraints[1]:
    authRoles[0]: ROLE_MANAGER
  securityCollections[1]:
    patterns: /manager


