CONNECT SYSTEM/oracle;

ALTER SESSION SET CONTAINER = ORCLPDB1;
CREATE TABLESPACE KEYCLOAKLAB_TBS DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/keycloaklabtbs01.dbf' SIZE 100M ONLINE;
CREATE TABLESPACE IDX_KEYCLOAKLAB_TBS DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/idx_keycloaklabtbs01.dbf' SIZE 100M;
CREATE USER KEYCLOAKLAB IDENTIFIED BY KEYCLOAKLAB DEFAULT TABLESPACE KEYCLOAKLAB_TBS TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION, ALTER SESSION, CREATE VIEW, CREATE TABLE, CREATE SEQUENCE TO KEYCLOAKLAB;
GRANT CREATE SYNONYM, CREATE DATABASE LINK TO KEYCLOAKLAB;
ALTER USER KEYCLOAKLAB QUOTA UNLIMITED ON KEYCLOAKLAB_TBS;